### ISSUE TITLE
path.extname is deprecated.

### ISSUE THREAD

**Issue by Nuxciel** [xndcn/symbols-tree-view#148] opened 2017-02-15 03:02 UTC
Argument to `path.extname` must be a string
```
Object.extname (/opt/atom/resources/app.asar/src/electron-shims.js:20:10)
TagGenerator.getLanguage (/home/orion/.atom/packages/symbols-tree-view/lib/tag-generator.coffee:40:25)
TagGenerator.generate (/home/orion/.atom/packages/symbols-tree-view/lib/tag-generator.coffee:81:29)
SymbolsTreeView.generateTags (/home/orion/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:223:62)
SymbolsTreeView.populate (/home/orion/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:107:14)
<unknown> (/home/orion/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:272:24)
```

**Comment by XachaB** [comment] 2017-04-07 09:14
Hi,

I fixed this in my local copy by changing the line 27 of tag-generatof.coffee to :


      return 'Cson' if (@path && path.extname(@path) in ['.cson', '.gyp'])


As I understand it, @path can be undefined, as it is obtained by doing `filePath = editor.getPath()`.
Note that this is my first time looking at atom's code and at coffee script, which is why I'm not contributing code directly, but this seemed transparent enough.

**Comment by ooJerryLeeoo** [comment] 2017-04-10 13:30
@XachaB you can open a `pull request` for this :+1: .

**Comment by jerrykal** [comment] 2017-04-10 13:49
@xndcn Can you take a look??

I think @XachaB's solution is awesome 👍

**Comment by XachaB** [comment] 2017-04-10 14:20
I did make a pull request, but I'd rather someone verify if this the correct way to check for undefined values. I did test on a minimal example on http://coffeescript.org/, and it looks like it's working locally on my machine, but I'm wondering if it wouldn't be better to use the existential "?" and write:

    return 'Cson' if (@path? && path.extname(@path) in ['.cson', '.gyp'])

**Comment by nicolashainaux** [comment] 2017-04-11 13:39
I am no coffee script expert either, but `@path?` looks like the correct way of writing this.
I will include this in the next release (0.15.3) of my [forked version](https://atom.io/packages/symbols-tree-nav).

It would have been interesting though to know what exactly triggers the bug (maybe files without extension?).

**Comment by sarangjo** [comment] 2019-06-11 21:41
Duplicate of #140

**Closed by sarangjo** 2019-06-11 21:41 UTC
