### ISSUE TITLE
Indent Markdown headings according to level

### ISSUE THREAD

**Issue by adunning** [xndcn/symbols-tree-view#58] opened 2015-07-19 20:53 UTC
Thanks for creating this package. Could Markdown headings be indented according to their hierarchical level, so that the following:

```markdown
# heading 1
## heading 2
### heading 3
# heading 1
```

… would display like this?

```
heading 1
  heading 2
    heading 3
heading 1
```

**Comment by blah-blah** [comment] 2015-08-14 20:40
In `.atom/packages/symbols-tree-view/lib/.ctags` you could change `--regex-Markdown=/^#+[ \t]*([^#]+)/\1/f,function/` to `--regex-Markdown=/^(#+)[ \t]+([^#]*)/\1 \2/h,header,Markdown Headers/`. That will mimic indentation to some extent by not stripping out the preceding #s. I stole the idea from [here](https://github.com/majutsushi/tagbar/issues/70#issuecomment-30392593).

**Comment by brettz9** [comment] 2015-10-26 18:57
This seems like it may be a dupe of issue #17

**Closed** 2015-10-26 19:42 UTC
